### ISSUE TITLE
Eraser is not round

### ISSUE THREAD

**Issue by smallamao** [Harley-xk/MaLiang#11]
When I change to eraser mode ,the brush is not round ,
but the texture image 'point.png' is round,
then I change eraser color to red 
can see the red round with white border

**Comment by Boca007** [comment]
try this. 

brush.swift
open class Eraser: Brush {
    
    /// only a global eraser needed
    public static let global = Eraser()
    
    private init() {
        let texture = MLTexture(image: BundleUtil.image(name: "point")!.cgImage!)
        texture.gl_blend_enabled = false
        super.init(texture: texture)
        pointSize = 60
        opacity = 1
        forceSensitive = 0
	color = UIColor(white: 0.0, alpha: 1.0)
    }
    
    // color of eraser can't be changed
//	override open var color: UIColor {
//        get {
//            return .clear
//        }
//        set {
//            // set color of eraser will do nothing
//        }
//    }
}

MLView.swift
    open var texture: MLTexture! {
        didSet {
            cacheTextureIfNeeds(texture)
            glBindTexture(GL_TEXTURE_2D.gluint, texture.gl_id)
            if texture.gl_blend_enabled {
		glBlendEquation(GL_FUNC_ADD.gluint)
		glBlendFunc(GL_ONE.gluint, GL_ONE_MINUS_SRC_ALPHA.gluint)
            } else {
		glColor4f(0, 0, 0, 0)
		glBlendEquation(GL_FUNC_REVERSE_SUBTRACT.gluint)
		glBlendFunc(GL_SRC_ALPHA.gluint,GL_ONE_MINUS_SRC_ALPHA.gluint)
            }
        }
    }


hope working for U too. :)

**Comment by make1a** [comment]
我也碰到了同样的问题 @Harley-xk  2L的解决方法似乎在上色之后就无效了。博主可以帮忙解决一下嘛

**Comment by make1a** [comment]
@smallamao  -----red round with white border.
try this:
```
- (void)disableBLEND{
    [EAGLContext setCurrentContext:context];
    glDisable(GL_BLEND);
    glColor4f(0, 0, 0, 0);
}
- (void)enableBLEND{
    [EAGLContext setCurrentContext:context];
    glEnable(GL_BLEND);
}
```

**Comment by Harley-xk** [comment]
resolved in the new Metal branch
