### ISSUE TITLE
使用ChartletBrush绘制后保存，重新读取丢失

### ISSUE THREAD

**Issue by jeruik** [Harley-xk/MaLiang#110]
下载demo，使用ChartletBrush绘制-保存-Data loading,重新打开，显示空白

**Comment by BreGit** [comment]
请问这个问题你解决了吗？目前我的项目中也需要用到这个功能

**Comment by jeruik** [comment]
解决了吧，当时不知道改了源码哪里，过了好久了，作者也不维护了，
