### ISSUE TITLE
is there a way to get the draw strokes points ?

### ISSUE THREAD

**Issue by X901** [Harley-xk/MaLiang#120]
Hi , 
when using PencilKit you can get strokes points , and you can redraw the points 
is there something like that I can do with the library ?

**Comment by Harley-xk** [comment]
Yes, All points are stored in the "data" property of Canvas

发自我的iPhone

**Comment by X901** [comment]
> Yes, All points are stored in the "data" property of Canvas 发自我的iPhone
> […](#)

I did check `.data` but I cannot access points

to give you Idea what I want to do is  I need to reach points so I can match between
what it was drew and what user drawing

**Comment by Harley-xk** [comment]
@X901 There's a property called `elements` on the class `CanvasData`, whitch is the type of `data` property on `Canvas`. All elements are follow the `CanvasElement` protocol. Includes lines(`LineStrip`) you draw on the canvas. 
A `LineStrip` is constructed by several `MLLine`s, a `MLLine` is a strait line contains two points for begin and end, and other properties such as color, size etc.

**Comment by Harley-xk** [comment]
@X901  There are two builtin tools called `DataExporter` and `DataImporter`. You can export all points and other elements data into a JSON file with `DataExporter` and then import them to another canvas on even other devices later by `DataImporter`.

**Comment by X901** [comment]
Thank you ,but it looks like I will need sometimes to understand the data.
