### ISSUE TITLE
不支持MacOS系统吗？

### ISSUE THREAD

**Issue by Zss1990** [Harley-xk/MaLiang#125]
在podfile文件中中添加`pod 'MaLiang'`，然后进行`pod install`，会有如下报错：
[!] The platform of the target `xxxxx-target` (macOS 11.0) is not compatible with `MaLiang (2.9.2)`, which does not support `macOS`.

**Comment by Harley-xk** [comment]
@Zss1990 现在只能通过 Catalyst 方式支持 macOS

**Comment by Harley-xk** [comment]
这个库是针对移动端开发的，Metal 在 macOS 上的表现与移动端不完全一致，并且 UI 方面的 API 差别巨大，暂时没有精力去做适配了
