### ISSUE TITLE
Brush color and multiply

### ISSUE THREAD

**Issue by ant3dstudio** [Harley-xk/MaLiang#126]
How to set the color for the ChartletBrush?

How to remove the blending of a brush?

Thanks!))

**Comment by Harley-xk** [comment]
Color of Chartlet Brush Can't be changed now,  It‘s only used to print images to canvas.
Also, blendings can't be removed too. Instead, you can override the `setupBlendOptions` method on your own brush.

**Comment by ant3dstudio** [comment]
yes, I change the color of the brush, just paint over the image with a color, but I can not figure out how to apply the fill to the texture in the class.

setupBlendOptions - not applicable, I can't figure out what's wrong.

Can you tell me what parameters should be applied so that the brush draws like  ChartletBrush?

Thanks!

**Comment by Harley-xk** [comment]
If you want to make your own chartlet brush, just extends your brush from the `Printer` class, like the `ChartletBrush` class do. In the `Printer` there are all settings for your needs, not only blend options,  but also shader functions.
