### ISSUE TITLE
Undo and Redo doesn't work

### ISSUE THREAD

**Issue by sweetcodestar** [Harley-xk/MaLiang#127]
Thank you for your this library.
I am using this code to draw lines but the undo and redo doesn't work.
I just attached a video.
Can you please let me know how to fix this problem?

https://user-images.githubusercontent.com/20561207/159237268-34f5a003-6011-4d56-80ee-bfa69e40122a.mp4

Regards.

**Comment by Harley-xk** [comment]
does this only occur on the simulator? It works well on my real device.

**Comment by sweetcodestar** [comment]
thanks for your message. it doesn't occur in real device exactly but there is another problem on real device.
I just added a new video.

https://drive.google.com/file/d/1WAh897HlzKjH8YAAjvkejTHR_FE2GO_h/view?usp=sharing

Thanks.

**Comment by sweetcodestar** [comment]
hi @Harley-xk.
do you have any idea about undo/redo issue?

**Comment by Harley-xk** [comment]
I can't reporduce the probelm, what's the model and system of your device?

**Comment by sweetcodestar** [comment]
my device is iphone 12 mini and ios is 15.1

**Comment by sweetcodestar** [comment]
I am sorry, I was using old code. I have downloaded final one and tested it. It working well. Thanks.
