### ISSUE TITLE
does this library support drawing to pdf?

### ISSUE THREAD

**Issue by lexuanquynh** [Harley-xk/MaLiang#138]
does this library support drawing to pdf?

**Comment by Harley-xk** [comment]
No, there's noting about pdf. you can take a snapshot from canvas and then draw that snapshot to some pdf file with any other pdf library

**Comment by lexuanquynh** [comment]
Okay, I created a repo for painting PDF files, but your library doesn't seem to be used. I'll leave the link for anyone who asks the same question I did. thank for your response.
https://github.com/lexuanquynh/PaintPDFApp
