### ISSUE TITLE
iPhone X 画板放大缩小 之前的路径会消失

### ISSUE THREAD

**Issue by liufsd** [Harley-xk/MaLiang#14]
您好，在iPhone X上发现一个很奇怪的bug：
1. 正常情况下画一条线
2.放大画板再画一条线
3.缩小画板，画线，此时之前的两条线都没有了的

发现问题卡在第三步，如果直接缩放的比例非常小，由于设置了最小缩放？？？，所以手松开会回弹一下到稍微大一点的比例，然后再进行绘制，就会丢失之前的数据，如果是正常慢慢缩小没问题的。

您觉得是什么原因导致的呢？

**Comment by liufsd** [comment]
你可以用你的demo中的scrollable试试，问题一样也是存在的。

**Comment by liufsd** [comment]
MLView 中的layoutSubviews 会在缩放过程中调用resize，然后再次进行绘制的时候数据就没有了的，跟了一下也没有调用你clear方法，路径却没有了的，试了一下，去掉resize就可以了的
why ???  帮忙一起分析一下原因？
```
 
    override open func layoutSubviews() {
        
        EAGLContext.setCurrent(context)
        
        if !initialized {
            initialized = initGL()
        } else {
            resize(from: glLayer)
        }
        
        // Clear the framebuffer the first time it is allocated
        if needsClear {
            clear(display: false)
            needsClear = false
        }
    }   

```

**Comment by liufsd** [comment]
不调用 resize 的话 放大之后 手按压的位置和画线的位置会偏移。

**Comment by Harley-xk** [comment]
缩放这块只是借助 ScrollView 简单实现了一个 demo，并不完善，应该会存在很多问题的。
实际应用的话还需要做很多优化，或者可能需要脱离 ScrollView 单独实现。。。

**Comment by Harley-xk** [comment]
> 你可以用你的demo中的scrollable试试，横屏操作，问题一样也是存在的。
> 
> iphone x 横屏 这个问题必现的， 之前在画之前进行了缩放，再接着画，之前的路径都没有了的。
> iPhone 7 同样也有这个问题
> ios 12
> 
> 我暂时没有头绪，不知道是什么原因导致的

视图尺寸发生变化（包括旋转屏幕），会触发 resize 事件，目前只是清空了视图，需要重新将 `document` 中的数据绘制到画布中。不清空的话，如果画布长宽不一致，旋转之后的图像会被拉伸。

**Comment by liufsd** [comment]
这就比较尴尬了的，有什么好的办法解决这个问题么？

**Comment by liufsd** [comment]
> > 你可以用你的demo中的scrollable试试，横屏操作，问题一样也是存在的。
> > iphone x 横屏 这个问题必现的， 之前在画之前进行了缩放，再接着画，之前的路径都没有了的。
> > iPhone 7 同样也有这个问题
> > ios 12
> > 我暂时没有头绪，不知道是什么原因导致的
> 
> 视图尺寸发生变化（包括旋转屏幕），会触发 resize 事件，目前只是清空了视图，需要重新将 `document` 中的数据绘制到画布中。不清空的话，如果画布长宽不一致，旋转之后的图像会被拉伸。

看代码是调用了resize ，没有直接看到清空的地方，清空是发生在，缩放之后，开始画新的线条的时候，之前的数据就没有了的，我想如果‘不清空’ 是不是就好了的呢？

**Comment by Harley-xk** [comment]
触发 layoutSubviews 之后缓冲区被被系统清空了，所以重新绘制时笔迹都丢失了。
更新了 1.1.7 版本，layoutSubviews 之后执行了一次重绘操作，应该可以解决这个问题了。

**Comment by liufsd** [comment]
好，我后天回来试试。感谢🙏
