### ISSUE TITLE
大佬，如何实现钢笔的笔触？

### ISSUE THREAD

**Issue by dyljqq** [Harley-xk/MaLiang#142]
可以提供一下实现的参数么？

**Comment by Harley-xk** [comment]
demo 里面有钢笔的，可以参考下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月30日(周二) 下午3:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Harley-xk/MaLiang] 大佬，如何实现钢笔的笔触？ (Issue #142)




 
可以提供一下实现的参数么？

**Comment by dyljqq** [comment]
> demo 里面有钢笔的，可以参考下
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年4月30日(周二) 下午3:09 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [Harley-xk/MaLiang] 大佬，如何实现钢笔的笔触？ (Issue #142) 可以提供一下实现的参数么？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

您好，你的demo里貌似并没有pen这种笔触，但是您的作品maliang App里是有的。

**Comment by Harley-xk** [comment]
时间太久远有点记不清了😂，钢笔纹理其实很简单，就是一个椭圆：
![texture-pen](https://github.com/Harley-xk/MaLiang/assets/12761885/3ba9ff25-16ee-46a9-95c9-4e9cb12a20af)

**Comment by dyljqq** [comment]
> 时间太久远有点记不清了😂，钢笔纹理其实很简单，就是一个椭圆： ![texture-pen](https://private-user-images.githubusercontent.com/12761885/328562677-3ba9ff25-16ee-46a9-95c9-4e9cb12a20af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMzI1MTEsIm5iZiI6MTcxNTEzMjIxMSwicGF0aCI6Ii8xMjc2MTg4NS8zMjg1NjI2NzctM2JhOWZmMjUtMTZlZS00NmE5LTk1YzktNGU5Y2IxMmEyMGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDAxMzY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNTcxMzVhOWY0ZWQwYWFkNGEwODRiY2JlOTdhMzlmZTIwYjgyNmM2MWU4YWNmM2E3NDQzNDM2ZjVjMDg4NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uI27crUET6w1jXiLxVGI0npUgQ1XWUf9jWhb2x_1aGY)
确实有点久远了。但我也记错了，之前不管是马良还是您提供的demo，其实只改变了线条的粗细，根据压感跟速度。但是我看到apple自己的无边记提供的钢笔笔触，就很炫酷，更像是现实中的钢笔。

**Comment by Harley-xk** [comment]
确实，马良的实现属于比较简单的，要实现 apple 的那种笔触比较复杂，不是简单画点就可以的了。

**Comment by dyljqq** [comment]
> 确实，马良的实现属于比较简单的，要实现 apple 的那种笔触比较复杂，不是简单画点就可以的了。

别趴大佬，我看市面上大部分的钢笔笔触都跟马良一样的，包括good notes，也只是改变了线条的粗细，牛马了。Apple Pencil的底层渲染器也是直接基于metal的。

**Comment by Harley-xk** [comment]
> 别趴大佬，我看市面上大部分的钢笔笔触都跟马良一样的，包括good notes，也只是改变了线条的粗细，牛马了。Apple Pencil的底层渲染器也是直接基于metal的。

Apple 的实现比其他家都要复杂一点，仔细看可以发现它的笔迹在收笔之后还会有微调的，应该是还有后期处理的步骤，这是算法层面的事，无关引擎了

**Comment by dyljqq** [comment]
> > 别趴大佬，我看市面上大部分的钢笔笔触都跟马良一样的，包括good notes，也只是改变了线条的粗细，牛马了。Apple Pencil的底层渲染器也是直接基于metal的。
> 
> Apple 的实现比其他家都要复杂一点，仔细看可以发现它的笔迹在收笔之后还会有微调的，应该是还有后期处理的步骤，这是算法层面的事，无关引擎了

对的，会有浸水的效果。

**Comment by dyljqq** [comment]
> > 别趴大佬，我看市面上大部分的钢笔笔触都跟马良一样的，包括good notes，也只是改变了线条的粗细，牛马了。Apple Pencil的底层渲染器也是直接基于metal的。
> 
> Apple 的实现比其他家都要复杂一点，仔细看可以发现它的笔迹在收笔之后还会有微调的，应该是还有后期处理的步骤，这是算法层面的事，无关引擎了

我们产品目前希望我们，去除这种收笔之后的效果，说有延迟感，牛马了。完全实现不可实现。
