### ISSUE TITLE
是否可以写一个Metal版本的呢？

### ISSUE THREAD

**Issue by liufsd** [Harley-xk/MaLiang#16]
OpenGL ES 在ios 12上已经被标记为废弃了的。

https://developer.apple.com/ios/whats-new/

Deprecation of OpenGL ES
Apps built using OpenGL ES will continue to run in iOS 12, but OpenGL ES is deprecated in iOS 12. Games and graphics-intensive apps that previously used OpenGL ES should now adopt Metal.

Metal is designed from the ground up to provide the best access to the modern GPUs on iOS, macOS, and tvOS devices. Metal avoids the overhead inherent in legacy technologies and exposes the latest graphics processing functionality. Unified support for graphics and compute in Metal lets your apps efficiently utilize the latest rendering techniques. For information about developing apps and games using Metal, see the developer documentation for Metal, Metal Performance Shaders, and MetalKit.

**Comment by Harley-xk** [comment]
MaLiang 是基于多年前的一个绘图项目改进而来的，所以一直沿用了 OpenGL。
确实有迁移到 Metal 的想法，我对 Matal 的学习深度还不够，另外精力也不是很够，一些技术问题暂时无法解决。。。
所以短期应该还没有计划吧

**Comment by Harley-xk** [comment]
研究了一下，打算基于 CoreGraphics 把底层实现重构，这样就不需要直接跟 Metal 打交道了。
等我先弄个 Demo 测试下性能吧

**Comment by liufsd** [comment]
好的。有问题和进展及时沟通吧。

**Comment by jerryhu** [comment]
@Harley-xk CoreGraphics实现底层，性能不如OpenGL ES, 这个绘画App就是CoreGraphics实现的 https://itunes.apple.com/cn/app/id380447096?mt=8

**Comment by liufsd** [comment]
![image](https://user-images.githubusercontent.com/1910405/48105725-9264dc00-e273-11e8-93b6-73c95c0778e3.png)
所以还是要趟一趟Metal ？ 不过Metal资料确实很少很少的。

**Comment by Harley-xk** [comment]
潜水 Metal 中。。。

**Comment by liufsd** [comment]
@Harley-xk 工作量还是很大的~

**Comment by Harley-xk** [comment]
@liufsd 底层已经迁移到 MetalKit，正在重构上层逻辑

**Comment by Harley-xk** [comment]
初步迁移完毕，正在进一步优化
