### ISSUE TITLE
Not compiled in latest version(1.1.8) of MaLiang

### ISSUE THREAD

**Issue by superITdev** [Harley-xk/MaLiang#17]
Hi, dear.

I tried to build the Example in MaLiang downloads with pod install with cocoa pods.
Here is the Podfile where I did new line, pod 'MaLiang' for Maliang.
-------------
use_frameworks!

target 'MaLiang_Example' do

pod 'Comet'
pod 'MaLiang'

end
-------------

But, many erros arise when build.
For example, 
---------------
MaLiang-1.1.8/Example/Pods/Comet/Comet/Extensions/UIAlertController+Comet.swift:13:64: 'Style' is not a member type of 'UIAlertAction'
MaLiang-1.1.8/Example/Pods/Comet/Comet/Extensions/UIBarButtonItem+Closure.swift:17:69: 'Style' is not a member type of 'UIBarButtonItem'
MaLiang-1.1.8/Example/Pods/Comet/Comet/Classes/KeyboardManager.swift:92:91: Type 'UIResponder' has no member 'keyboardWillShowNotification'
MaLiang-1.1.8/Example/Pods/Comet/Comet/Classes/KeyboardManager.swift:94:90: Type 'UIResponder' has no member 'keyboardDidShowNotification'
MaLiang-1.1.8/Example/Pods/Comet/Comet/Classes/KeyboardManager.swift:95:98: Type 'UIResponder' has no member 'keyboardWillChangeFrameNotification'
MaLiang-1.1.8/Example/Pods/Comet/Comet/Classes/KeyboardManager.swift:149:42: Type 'UIResponder' has no member 'keyboardAnimationDurationUserInfoKey'
MaLiang-1.1.8/Example/Pods/Comet/Comet/Extensions/UIVIew+Comet.swift:65:98: 'OptionsKey' is not a member type of 'UINib'
MaLiang-1.1.8/Example/Pods/Comet/Comet/Classes/KeyboardManager.swift:150:26: Type 'UIView' has no member 'AnimationOptions'
MaLiang-1.1.8/Example/Pods/Comet/Comet/Classes/KeyboardManager.swift:167:34: Type 'UIResponder' has no member 'keyboardFrameEndUserInfoKey'
MaLiang-1.1.8/Example/Pods/Comet/Comet/Classes/KeyboardManager.swift:180:22: Type 'UIView' has no member 'AnimationOptions'
MaLiang-1.1.8/Example/Pods/Comet/Comet/Extensions/UINavigationBar+Comet.swift:27:59: Type 'NSAttributedString' has no member 'Key'

...

MaLiang-fgkbrzhxgpualzdixhtqfoxfrjaj/Build/Products/Debug-iphoneos/Comet/Comet.framework/Modules/module.modulemap:9:12: Header 'Comet-Swift.h' not found
MaLiang-1.1.8/Example/MaLiang/ViewController.swift:10:8: Could not build Objective-C module 'Comet'
Command Ditto failed with a nonzero exit code
---------------

Would you help me, please ?
Thanks.

**Comment by Harley-xk** [comment]
Please update the swift version of your project to **swift 4.2**

**Comment by superITdev** [comment]
Fixed as your guidance.
Thank you.

Sent from Outlook<http://aka.ms/weboutlook>
________________________________
