### ISSUE TITLE
老哥，TODO中的内容实现了嘛

### ISSUE THREAD

**Issue by CoderMaurice** [Harley-xk/MaLiang#19]
正好需要这方面的资料参考，刚好看到这个项目 非常棒👍

请问，这俩功能有计划更新吗?

- 绘制文本到画布中的指定位置
- 绘制指定的图片到画布中的指定位置

**Comment by Harley-xk** [comment]
目前还没有实现，最近事情比较多，可能要过一阵子

**Comment by CoderMaurice** [comment]
想把这个项目改一个OC版本，苦于对Swift不是特别熟悉 

请问 

        vsrc.withUnsafeBytes {(vsrcChars: UnsafePointer<GLchar>) in
            
            // auto-assign known attribs
            for (j, name) in attribName.enumerated() {
                if strstr(vsrcChars, name) != nil {
                    attrib.append(GLuint(j))
                    attribUsed.append(name)
                }
            }
            
            fsrc.withUnsafeBytes {(fsrcChars: UnsafePointer<GLchar>) in
                _ = ShaderUtil.createProgram(UnsafeMutablePointer(mutating: vsrcChars), UnsafeMutablePointer(mutating: fsrcChars),
                                             attribUsed, attrib,
                                             uniformName, &shaderProgram.uniform,
                                             &prog)
            }
        }

这个方法的作用是什么呢，用OC怎么写?

**Comment by Harley-xk** [comment]
这里有官方 OC 版的示例代码,不过只有最核心的绘图部分的:
