### ISSUE TITLE
X and Y start point coordinate issue on ipad and phone

### ISSUE THREAD

**Issue by rahulglemaing** [Harley-xk/MaLiang#20]
Hi MaLiang,

This is very helpful.But when I'm trying to draw lines with pen, but not connected two line. It only recognizes every second stroke and does not start writing at exact point of contact. When I'm zooming then it's more skip point instead of start point.

Please help me ASAP. Please review attached screenshot for understand issues.
![simulator screen shot - ipad pro 12 9-inch 2nd generation - 2019-01-22 at 18 54 32](https://user-images.githubusercontent.com/46927747/51538481-6969e580-1e77-11e9-920d-33e87489f2a0.png)

Thank You MaLiang.

**Comment by Harley-xk** [comment]
Fixed this issue in version 1.1.9
Thanks for using MaLiang :)

**Comment by rahulglemaing** [comment]
Thanks You very much Harley, I like this Library.

**Comment by rahulglemaing** [comment]
I'm creating demo for.  I am trying try to draw like cloud(zagged) pattern, but didn't understand pattern like in attached screenshot. Can you help me 
![screen](https://user-images.githubusercontent.com/46927747/51826087-3c508380-230c-11e9-813a-f107500e4882.png)
for this pattern?

Thank you and Regards
Rahul

**Comment by Harley-xk** [comment]
MaLiang does not support gradient patten now, you can use a translucent texture to make a similar one.
