### ISSUE TITLE
Line is not drawing during zoom in sometimes.

### ISSUE THREAD

**Issue by rahulglemaing** [Harley-xk/MaLiang#22]
Hello Harley,

Please review attached video, I am facing problem when zoomed and drawing very sort line(draw line in " v" shape), then some times got only tap gesture instead of pan gesture.

It's working normal zoom mode, getting issues when zoom in only
[DrawingDemo Issues video.mov.zip](https://github.com/Harley-xk/MaLiang/files/2831997/DrawingDemo.Issues.video.mov.zip)

.

Please help me.

Thanks and Regards
Rahul

![screen shot 2019-02-05 at 5 34 08 pm](https://user-images.githubusercontent.com/46927747/52272268-46a5f980-296c-11e9-9f9a-391815c400ec.png)

**Comment by Harley-xk** [comment]
zoom and scale have been reconstructed in the Metal Version, this issue should have been resolved

**Comment by Harley-xk** [comment]
@rahulglemaing try the new Metal Version
