### ISSUE TITLE
'Eraser' can't be found ???

### ISSUE THREAD

**Issue by chiefky** [Harley-xk/MaLiang#23]
发现一个问题：Cocoapods引入后，Eraser 使用时会报这个error。手动引入工程的话没有问题。

<img width="1076" alt="bca67bef-2552-497a-93bc-25f68aac9321" src="https://user-images.githubusercontent.com/3211717/52850002-64821400-314d-11e9-84cd-4edc3c3f22ab.png">
你提供的example换成pod 引入也存在这个问题：

<img width="1403" alt="300f0f51-5bd8-48ba-9149-a03504d3f821" src="https://user-images.githubusercontent.com/3211717/52850925-bdeb4280-314f-11e9-94d1-e12de74de57e.png">

**Comment by Theak13** [comment]
Make Eraser class to open in Brush.swift file
```

// Eraser class
open class Eraser: Brush {
    
    /// only a global eraser needed
    public static let global = Eraser()
    
    private init() {
        let texture = MLTexture(image: BundleUtil.image(name: "point")!.cgImage!)
        texture.gl_blend_enabled = false
        super.init(texture: texture)
        pointSize = 10
        opacity = 1
        forceSensitive = 0
    }
    
    // color of eraser can't be changed
  override open var color: UIColor {
        get {
            return .clear
        }
        set {
            // set color of eraser will do nothing
        }
    }
}
```

**Comment by Harley-xk** [comment]
fixed in 2.0
