### ISSUE TITLE
When is the Release of "Text element", "Image element" & "Texture rotation"?

### ISSUE THREAD

**Issue by sohilmemon** [Harley-xk/MaLiang#24]
Can I know when you are going to make availabe the remaining features? I am eagerly waiting for it?

**Comment by rashidabbas** [comment]
Please complete remaining features I am using your project it awesome. text element and image element are very important features.

**Comment by Harley-xk** [comment]
in development

**Comment by sohilmemon** [comment]
> in development

Thanks! Can't wait to see it :D Also I need to see how can I apply shaders to the bush 💃

**Comment by Harley-xk** [comment]
@sohilmemon what kind of shaders? usually you only needs to make a new texture

**Comment by sohilmemon** [comment]
> new

Please check out this app, it's using different kind of shaders while drawing, glowing, blending, and various others:

https://apps.apple.com/bh/app/magic-doodle-movie-color-draw/id460712294

**Comment by Harley-xk** [comment]
em... it's really excellent. Blending options is currently overridable, you can refer to the implementation of Eraser for details. And maybe I should make the pipelineState and render function overridable too.

**Comment by sohilmemon** [comment]
Ok thanks will surely look into it! Other than that I am using the attached brush but it doesn't rotate as the finger draw.

Please check and let me know how can I implement it!
![shape_8](https://user-images.githubusercontent.com/9163419/56416276-ffae7b80-62ad-11e9-9923-26ab7528383b.png)

**Comment by Harley-xk** [comment]
Texture rotation is just in the planning map now. To implement this, some kind of matrix should be set to the texture coordinate in the vertex shader functions to rotate the result of texture sampler.

**Comment by sohilmemon** [comment]
> Texture rotation is just in the planning map now. To implement this, some kind of matrix should be set to the texture coordinate in the vertex shader functions to rotate the result of texture sampler.

Yes, I saw that in OpenGL shader but it's hard to implement in Metal and I am totally new to it!

**Comment by Harley-xk** [comment]
I will try to make it these days, give me some time :)

**Comment by sohilmemon** [comment]
> I will try to make it these days, give me some time :)

Sure thanks man :)

**Comment by Harley-xk** [comment]
@sohilmemon @rashidabbas Image element is ready now, and text element can be rendered to canvas 
using image element with a snapshot taken on the textviews or labels

**Comment by Harley-xk** [comment]
I' will provide an UI component for snapshot later, and next thing is the texture rotation

**Comment by sohilmemon** [comment]
@Harley-xk Awesome man! Let me try it out now! Thank you so much :D

**Comment by rashidabbas** [comment]
@Harley-xk Its Awesome man! Can you please give me a favour to add selection tool in this repo.

**Comment by Harley-xk** [comment]
@rashidabbas I’m doing this now

**Comment by rashidabbas** [comment]
> @rashidabbas I’m doing this now

Thanks a lot man.

**Comment by Harley-xk** [comment]
@rashidabbas I have added a simple chartlet editor in to the sample project, check out the latest code and have a try

**Comment by Harley-xk** [comment]
@sohilmemon @rashidabbas texture rotation is finished, checkout and have a try

**Comment by sohilmemon** [comment]
This is something amazing! Let me give a shoot and I will update you if anything I found! Thanks a lot man :D

**Comment by sohilmemon** [comment]
Can I ask you question? Where do you learn to write metal shaders so efficiently?

**Comment by Harley-xk** [comment]
@sohilmemon em... I'm learning it yet, and only knows very little.

**Comment by Harley-xk** [comment]
I'll close this issue, open a new one if you've found anything wrong.

**Comment by sohilmemon** [comment]
Any update on Text Element, which has the ability to do the following things?

1) Text can be added to Canvas
2) Can able to change fonts
3) Text alignment
4) Text Size
5) Transformation like "Underline, Bold, etc."
