### ISSUE TITLE
xs max 启动crash

### ISSUE THREAD

**Issue by liufsd** [Harley-xk/MaLiang#28]
![image](https://user-images.githubusercontent.com/1910405/56087690-8cb69680-5ea2-11e9-88e2-d3a60424b3fa.png)

**Comment by Harley-xk** [comment]
能贴一下控制台具体的log吗

**Comment by liufsd** [comment]
刚才升级了一下电脑系统，重启之后，打开xcode编译，竟然好了的？？？？
