### ISSUE TITLE
你好，请问是不支持OC版本么？

### ISSUE THREAD

**Issue by birdmichael** [Harley-xk/MaLiang#29]
我现在已经在oc项目桥接上了。但是好像没有类和方法暴露

**Comment by Harley-xk** [comment]
嗯，这是纯 Swift 项目，没有支持 OC 的计划

**Comment by birdmichael** [comment]
好难受~~我桥接上了。。也可以用~~
但是一个方法都没暴露。。
我百度了一下 是否是加上open 和 public~~
是后面版本变动，需要显式申明@objc即可适配嘛？

**Comment by birdmichael** [comment]
好像@objcMembers就好了

**Comment by birdmichael** [comment]
我一会加好，测试一下，如果可以 给您提pr吧。。。谢谢大佬奉献

**Comment by Harley-xk** [comment]
@birdmichael 不是直接加 @objc 就可以的，很多底层类都是纯 Swift 实现的，包括一些协议、枚举等，是没法桥接到 OC 的
