### ISSUE TITLE
有个glBlendFunc 问题请教下

### ISSUE THREAD

**Issue by 12207480** [Harley-xk/MaLiang#3]
glBlendFunc(GL_ONE.gluint, GL_ONE_MINUS_SRC_ALPHA.gluint)
![image](https://user-images.githubusercontent.com/6346030/39861704-0151b4f0-5474-11e8-9358-a00b4dbb3cd7.png)

glBlendFunc(GL_ONE.gluint, GL_ZERO.gluint)
![image](https://user-images.githubusercontent.com/6346030/39861748-212ae530-5474-11e8-8a87-0207176c603e.png)

为什么差别这么大 ？目标颜色是多少？  对于这个混合glBlendFunc(GL_ONE.gluint, GL_ONE_MINUS_SRC_ALPHA.gluint) 我不太理解？ 请教下

**Comment by Harley-xk** [comment]
glBlendFunc 是用来做颜色混合的，设置不同的模式实际绘制的颜色会有很大的差别。
OpenGL 我也是知道一点皮毛，具体函数的用法网上应该有很多资料的，关于颜色混合函数帮你找到一篇：https://blog.csdn.net/aurora_mylove/article/details/1700540

**Comment by 12207480** [comment]
感谢
