### ISSUE TITLE
iPhone7 Plus遇到操作位置和显示位置不一致的情况

### ISSUE THREAD

**Issue by FunnyFzl** [Harley-xk/MaLiang#30]
试用了一下，确实优秀，但是在操作中有个点，个人觉得是存在bug 的。
随便打开一种画图模式，比如我选择的是第二个cell ，为了复现
1、我在页面画了三个圈（第一张图）
2、尽量在圈的中心方向 画一条线，都画了两遍
3、从屏幕从上到下不同位置三个圈画线来看，越往下，位置越偏移
4、第二张图是我在备忘录的画图模式按照同样的步骤操作的，能达到预期效果
ps：iPhone7 Plus，iOS12.2，希望越来越好

![IMG_C4A69A53881D-1](https://user-images.githubusercontent.com/15104149/56635033-a3c16980-6696-11e9-9cfe-7dfd286b3a4b.jpeg)
![IMG_B2172AE02F7D-1](https://user-images.githubusercontent.com/15104149/56635036-a6bc5a00-6696-11e9-9c82-086587170638.jpeg)

**Comment by Harley-xk** [comment]
更新到最新版本试一下还有问题吗，我试了下没有重现出来，画的时候有缩放画布吗
方便的话能否录个视频，我研究下具体什么原因

**Comment by FunnyFzl** [comment]
特意录了个视频，视频里你能明显的看到：我的手指在屏幕上半部分画线的时候，手指划过的路线和屏幕显示基本一致，在屏幕下半部分，偏移了不少，而且越往下，偏移越大。

[IMG_5234.MOV.zip](https://github.com/Harley-xk/MaLiang/files/3112159/IMG_5234.MOV.zip)

**Comment by FunnyFzl** [comment]
录视频的是clone 的最新版本，没有缩放

**Comment by Harley-xk** [comment]
确实，在 Xs 上是好的，我在 8p 上面重现了，我来看一下是什么原因

**Comment by Harley-xk** [comment]
@FunnyFzl 已修复，再试一下。应该是所有 plus 都存在的问题，plus 的实际 `contentScaleFactor` 是 2.6x，然而通过 UIScreen 拿到的 scale 却是 3，导致了误差的产生。

**Comment by FunnyFzl** [comment]
> @FunnyFzl 已修复，再试一下。应该是所有 plus 都存在的问题，plus 的实际 `contentScaleFactor` 是 2.6x，然而通过 UIScreen 拿到的 scale 却是 3，导致了误差的产生。

MaLiang 2.0.1 版本  问题还是存在

**Comment by Harley-xk** [comment]
应该是修好了的，是不是缓存没清，先执行 **Clean Build Folder** 之后再编译

**Comment by KishanMakk** [comment]
Hello still get this issue, any solution??
