### ISSUE TITLE
Missing `registerChartlet` method on Canvas

### ISSUE THREAD

**Issue by DamienBell** [Harley-xk/MaLiang#31]
First off thanks for sharing this great framework!
It looks like the 'registerChartlet' method is missing on the `Canvas` class. So we're getting an error in the `TextureElementSamples` view controller.

**Comment by Harley-xk** [comment]
Yes, this method is removed, use makeTexture on canvas instead, I will update the sample project later

**Comment by DamienBell** [comment]
cool, thanks

**Comment by Harley-xk** [comment]
@DamienBell I have just updated the sample project
