### ISSUE TITLE
画布放大时，画笔新画出的线条变细了，应该和之前的路径一样放大才是？

### ISSUE THREAD

**Issue by liufsd** [Harley-xk/MaLiang#32]
画布放大的时候，已经存在的线条是放大了的，那么我手指按下去画的新线条应该也是一样的放大才对，等缩放回去之后，一起等比缩放到原来的线条。
是不是这样才符合大家的使用习惯呢？

**Comment by Harley-xk** [comment]
参考 #18 ,两种需求都存在, 缩放画布线条粗细保持不变的话, 可以做一些微缩绘制之类的操作, 因为实现这样的效果需要一些底层的支持,所以新版本采用了这种策略. 如果想要线条随着缩放同步放大缩小的话,可以通过同步调整画笔尺寸来实现.

**Comment by liufsd** [comment]
我看到他的那个issue了的，我觉得他的意思和我应该是一个意思，旧线条放大，新画的却是细的，不太符合画板的设计吧。画布相关的App无论是PC和移动，都是这种思维，画板放大是矢量的放大，画笔不变的情况下，画出来的东西应该是当前画布的大小，而不是缩放之前的大小。

**Comment by Harley-xk** [comment]
个人理解不同吧，很多年前有个神级画图App叫 Draw me，现在好像已经找不到了，他可以放大画布之后对细节进行绘制，这个特性当时惊艳到了我，这也是现在MaLiang引入这个特性的灵感来源。
另外 MaLiang 只是一个库，而不是画板 App，所以我觉我应该提供更多的定制和扩展的可能，而不是去实现一个特定的需求。照顾使用习惯和用户体验应该是App这一层的工作。

**Comment by liufsd** [comment]
其实我一开始也是这么认为的，觉得放大之后是调细节，所以应该画出来是细小的，但是很多人反馈说这不对，因为画笔样式为做调整。放大只是处理某一个区域而已。

**Comment by liufsd** [comment]
而且个人认为这不是特殊定制需求，而是常规使用场景，你指的那个人的需求，我当时也看了，所以自己开发的时候就是按照他的说法来做的（放大或缩小，新线条也会跟之前的一样变化的）。

**Comment by Harley-xk** [comment]
画笔同步跟着放大其实并没有什么意义, 可操作区域变小了, 画笔变大了, 导致的结果就是什么也做不了.

**Comment by liufsd** [comment]
放大的作用是：是想在那个区域画东西，那么如果他想在那个区域画很小的线条，此时应该是用新的画笔去画。 但作为之前的画笔，画出来的新线条应该和刚才之前的线条同等的放大才对，否则同一只笔，为什么画出来的东西却不一样呢？

**Comment by Harley-xk** [comment]
正如我上面说的, 放大区域之后, 如果画笔跟着变大, 那么用户就做不了什么了,因为画笔太大了,特别是放大很多的时候,随便画一条线可能就占了小半个屏幕, 此时画笔已经没有意义了. 所以我认为用户放大画布的目的就是为了绘制更精细的内容, 此时画出的线条应该在视觉上与之前一样大, 这样用户放大画布之后不需要做任何操作就能继续绘画了. 我认为这也是画布放大这个功能唯一存在的意义.

不过为了更多的定制需求, 后面我针对这个特性增加一个控制参数决定画笔是否跟着同步缩放吧, 这样可以减少一些上层实现的工作量.

**Comment by liufsd** [comment]
我懂你的意思，但个人觉得sdk默认实现的效果应该是我刚才说的那种跟随者画布大小变化而变化，而至于你刚才那种效果，应该是可以做成配置的。
其次是，放大缩小如果画笔画新的线条保持原有的不变，那么在做数据恢复的时候，同一个画笔，可能会出问题的，比如两条线粗线会又一样了。
所以综上所属：还是建议画布缩放过程中，画笔跟随变化。

**Comment by Harley-xk** [comment]
`Brush` 新增了一个属性: `scaleWithCanvas`, 设置为 true 时, 画笔尺寸会随着画布同步缩放.
考虑到有其他人也使用了画布缩放的特性, 为了保证不影响原有的行为逻辑, `scaleWithCanvas` 默认设置为 `false`. 
另外这个特性不会影响到数据恢复, 保存到文件中的 MLLine 的尺寸数据是绘制时直接根据缩放值计算得到的, MLLine 本身不包含缩放信息.
我稍后更新下 README.

**Comment by liufsd** [comment]
是吧？ 我晚点试试，我记得当时在做数据回放的时候有一定的问题，当然我是把就的数据恢复到其他更小的画板上面去了。Metal版本我还没有尝试过，只是体验阶段。
你可以试试～

**Comment by Harley-xk** [comment]
Metal 版本很多底层逻辑都是重新实现的，特别是缩放这一块，原来 OpenGL 版本的缩放只是借助于 UIScrollVIew 的缩放功能实现的一个 Demo

**Comment by liufsd** [comment]
新版本的缩放这一块没看… 看到刚才讨论的那个画笔问题，我以为会跟之前一样的呢……哈哈哈
点赞👍
