### ISSUE TITLE
画笔颜色似乎有时候不对

### ISSUE THREAD

**Issue by liufsd** [Harley-xk/MaLiang#34]
![image](https://user-images.githubusercontent.com/1910405/56941281-20948d80-6b46-11e9-8ddb-b6d85691a016.png)

**Comment by liufsd** [comment]
但其实单击的时候看到的颜色是对的， 画线的颜色对不上。
![image](https://user-images.githubusercontent.com/1910405/56941340-710beb00-6b46-11e9-83dd-839aea29a2cf.png)

**Comment by Harley-xk** [comment]
混合参数不太对，我来调一下

**Comment by Harley-xk** [comment]
@liufsd 试一下 2.1.2 版本，应该可以了

**Comment by liufsd** [comment]
可以了的，赞👍。
有一个小的需求，我需要拿到MLColor，但是似乎访问不到这个结构体（以及熟悉），还有MLLine的一些变量。能改成public么？

**Comment by Harley-xk** [comment]
嗯……我来看一下，你需要访问这几个属性做什么呢？设计上 ML 开头的几个类是只用于内部逻辑的，按道理上层应该不需要直接访问，而且直接修改相关的值的话，可能会导致某些绘制过程出现错乱

发自我的 iPhone

**Comment by liufsd** [comment]
我只是想读取一下，每一条线条使用的是什么颜色，只是读一下GGB颜色，统计一下， 并不会去改变的。

**Comment by liufsd** [comment]
还有我看到了你的数据恢复：  canvas.data.elements = (content.lineStrips + content.chartlets).sorted(by: { $0.index < $1.index})

我想实现一个效果，就是一点点一条一条的按照用户之前的画的线条，帮他恢复过来。有好的思路么？
比如for循环的方式间隔一秒设置一下canvas.data.elements ，但是可能比较生硬，所以请教一下有什么好的思路没有呢？

**Comment by Harley-xk** [comment]
嗯，统计的话只要到 LineStrip 这一层就够了，一个 LineStrip 代表一条完整的线，MLLine 只是通过贝塞尔曲线算出来的一个个很短的线段，数量会很大。我晚点把 MLLine 相关的属性作为只读属性开放出来吧。
另外渐进地恢复数据也是我设想中的功能，目前可以重写DataImporter的相关函数来实现，比如设定一个定时器，每隔一段时间向canvas.data.elements加入数据，然后重绘画布。我后面会在框架层面加入这个功能，不过目前有更高优先级的其他功能要实现，这个特性会晚一些。

发自我的 iPhone

**Comment by liufsd** [comment]
嗯，好，我也在看这一块怎么实现canvas.data.elements加入数据。

**Comment by aUcidme** [comment]
您好，请问在图片上绘画是怎么实现的呢？

**Comment by liufsd** [comment]
@Harley-xk  好像调用一下导入文件，画板就恢复了数据？？？ 
设置canvas.data.elements似乎无效的？。？

**Comment by Harley-xk** [comment]
DataImporter 本身是一次性恢复数据的，我的意思是你需要自定义一个类继承DataImporter，然后重写数据导入过程的函数

**Comment by liufsd** [comment]
嗯，我懂的意思，不过我尝试去恢复，比如直接在你demo代码基础上修改canvas.data.elements，似乎没有作用。

**Comment by Harley-xk** [comment]
设置 `canvas.data.elements` 不会立即生效的，需要调用 `canvas.redraw()` 来重绘画布，参数全部默认就可以了

**Comment by liufsd** [comment]
没有办法来实现路径一点点恢复的效果，因为属性访问不到。
![image](https://user-images.githubusercontent.com/1910405/57566832-50277d80-7403-11e9-86b8-f985937ab58f.png)

**Comment by liufsd** [comment]
我想搞一个效果： 比如我先画了个 1 2 3  。那么点数据恢复的时候，是慢慢的画出来 1 2 3 ，感觉比较有趣~  不知道控制这个元素集合能否实现？ 不过感觉要一直不停的调用redraw， 不清楚性能如何？ 或者还有其他思路么？
