### ISSUE TITLE
可以提供个画荧光笔的思路么，类似下面这样的

### ISSUE THREAD

**Issue by zhangdongpo** [Harley-xk/MaLiang#35]
![IMG_BF3D36927E80-1](https://user-images.githubusercontent.com/15242207/56953605-86e1d600-6b6f-11e9-820d-0f9d7d73c3d4.jpeg)

**Comment by zhangdongpo** [comment]
http://nightwish.oss-cn-beijing.aliyuncs.com/2019-04-30-IMG_BF3D36927E80-1.jpeg

**Comment by Harley-xk** [comment]
Finished in 2.3.0
