### ISSUE TITLE
怎么实现在图片上绘画？

### ISSUE THREAD

**Issue by aUcidme** [Harley-xk/MaLiang#36]

**Comment by Harley-xk** [comment]
可以把 ImageView 和 Canvas 放到同一个父视图中，绘画完毕后对父试图截图可以获得合并在一起的图片。截图可以参考 Canvas 的 `snapshot` 方法。

**Comment by aUcidme** [comment]
好的，谢谢您的耐心回复，也很感谢您提供了这么好用的框架！
