### ISSUE TITLE
smooth brush strokes

### ISSUE THREAD

**Issue by abrpatel** [Harley-xk/MaLiang#37]
the brush strokes are not smooth, when the pointStep is 1 or less. How do you make the strokes smooth on the edges of the lines?

**Comment by Harley-xk** [comment]
@abrpatel Avoid using opaque textures, and make a gradient effect on the edge of your texture,  this will reduce the aliasing.

**Comment by abrpatel** [comment]
could you provide an example?

**Comment by Harley-xk** [comment]
create a brush with the image below, you can draw a smooth and solid line.
![pen](https://user-images.githubusercontent.com/12761885/57202613-ec075280-6fd9-11e9-942a-52036abf1fbb.png)

**Comment by abrpatel** [comment]
wow that worked. I'm trying to create a brush with the same properties, but can't replicate it. Could you either point to tutorial or give what alpha values and gradient settings you used to create the image above. 

Thank You!

**Comment by Harley-xk** [comment]
@abrpatel Above image is created by Photoshop. I just created a dot with gradient from black to clear, and the transparent of layer to 90%.

**Comment by abrpatel** [comment]
Amazing! Thank You!!
