### ISSUE TITLE
Brush Rotation

### ISSUE THREAD

**Issue by rashidabbas** [Harley-xk/MaLiang#38]
Hi @Harley-xk 

I am using your library into my project its awesome but I need one thing more that is missing in this library . just like texture rotation can we build brush painting rotation and selection from one place to other .

you can see selection tool in this library.

https://github.com/Asana/Drawsana

Thanks in advance.

**Comment by Harley-xk** [comment]
@rashidabbas I'm not clearly know what you means, Are you want to move the things draw by brush from one place to another?

**Comment by rashidabbas** [comment]
yes exactly I want selection tool if I draw something but I want to move after drawing .

**Comment by rashidabbas** [comment]
Drawsana library have selection tool but I am using your library because its working is awesome but missing this one tool. please make this tool it will be very useful.

**Comment by Harley-xk** [comment]
I'm afraid this currently is not supported, things can't be moved when they are paint to the canvas. Also there are no selection tools.

**Comment by rashidabbas** [comment]
but Drawsana have selection and move tool you can see.

https://github.com/Asana/Drawsana

**Comment by Harley-xk** [comment]
Yes, I have seen this project. The base implement of MaLiang is totally different,  so the tool from this project could not be used directly in my project. There are too much works to be done to make this feature working, and it's not in the plan now.

**Comment by Harley-xk** [comment]
If you have draw something wrong, just remove it using the undo function and then make a new one.
