### ISSUE TITLE
NSData support

### ISSUE THREAD

**Issue by abrpatel** [Harley-xk/MaLiang#39]
Is there a way to import and export canvas data directly to NSData. Right now the import and export type is to a file in the documents directory. This support is to allow saving the canvas to database persistence stores like core data or realm.

This is my initial attempt:

```
  public static func contentData(from canvas: Canvas) -> NSData? {
        do {
            let encoder = JSONEncoder()
            
            let data = canvas.data
            let content = CanvasContent(lineStrips: data?.elements.compactMap { $0 as? LineStrip } ?? [],
                                        chartlets: data?.elements.compactMap { $0 as? Chartlet } ?? [])
            
            let contentData = try encoder.encode(content)
            
            return contentData as NSData
        } catch {
            print(error.localizedDescription)
            
            return nil
        }
    }
```

```
   public static func importData(value: NSData, to canvas: Canvas) {
        if value.length > 0 {
            let decoder = JSONDecoder()
            
            DispatchQueue(label: "com.maliang.importing").async {
                do {
                    let content = try decoder.decode(CanvasContent.self, from: value as Data)
                    
                    /// import elements to canvas
                    content.lineStrips.forEach { $0.brush = canvas.findBrushBy(name: $0.brushName) }
                    content.chartlets.forEach { $0.canvas = canvas }
                    canvas.data.elements = (content.lineStrips + content.chartlets).sorted(by: { $0.index < $1.index})
                    
                    DispatchQueue.main.async {
                        /// redraw must be call on main thread
                        canvas.redraw()
                    }
                } catch {
                    DispatchQueue.main.async {
                        print(error.localizedDescription)
                    }
                }
            }
        }
    }
```

though not completely successful as the canvas isn't loading properly from the saved data.

**Comment by Harley-xk** [comment]
Have you set up all brushes used? They must be set up before importing data to the canvas.
And another thing, textures used by chartlets are also saved in to the file. you should recreate these textures before importing data too.

**Comment by abrpatel** [comment]
I'm exporting the line stripes and chartlets like so

```
let content = CanvasContent(lineStrips: data?.elements.compactMap { $0 as? LineStrip } ?? [],
                                        chartlets: data?.elements.compactMap { $0 as? Chartlet } ?? [])
```

when importing I'm unwrapping and assigning it to the canvas like so

```
content.lineStrips.forEach { $0.brush = canvas.findBrushBy(name: $0.brushName) }
content.chartlets.forEach { $0.canvas = canvas }
canvas.data.elements = (content.lineStrips + content.chartlets).sorted(by: { $0.index < $1.index})
```
         
Is this what you mean by setting up all the brushes used? I'm basically following the function importDataSynchronously as a reference to try to wrap and unwrap the data using JSONDecoder and save/retrieve the NSData to the local database.

If not, and example or the file / line numbers in the source code as a reference to how you've done do in the example project would be appreciated.

**Comment by Harley-xk** [comment]
Before draw lines with a brush, that brush must be registered to canvas first. So when you import lines' data in to the canvas, brushes to draw these lines must be already registered to that canvas, and the same as textures for chartlets. These works are not done by data importer, you should do it your self.
You can refer to the `viewDidLoad()` method of `ViewController` in the sample project.

**Comment by abrpatel** [comment]
Got it! 
One issue though, when you use a brush file for the eraser, it erasers fine, but when it loads back, it draws it as a solid line. The only way I found that it erases and loads well is to use the file name "maliang.eraser", as used in the sample project. Not a big issue, but one that I found interesting.

**Comment by Harley-xk** [comment]
@abrpatel Canvas will find brushes(including erasers) by the name specified in saved data to restore content. So, If you are using a customized eraser and attempting to save contents to data or files, make sure that you have registered it to canvas with an **unique name**, this name will then be written in to data or files on saving, this rule is same to all other brushes.

**Comment by abrpatel** [comment]
Thanks for the tip! I was using the same brush / name for the eraser.
