### ISSUE TITLE
Missing 'registerBrush' method on canvas

### ISSUE THREAD

**Issue by saumyalahera** [Harley-xk/MaLiang#41]
I followed your steps, however when I try to register a brush it gives me an error. 
Thank you for your time. Also, it works fine on your example project. But I want to use it on mine so I am having difficulties.

**Comment by Harley-xk** [comment]
which method did you call and what the error says ?

**Comment by saumyalahera** [comment]
Well. I figured out how to use a brush, but I cannot change colour. I mean, colour doesn't change. It is black. And also, your example project is very much different.

 let b1 = Brush(texture: UIImage(named: "pencil.png")!)
 b1.color = UIColor.red
 canvasView.brush = b1

**Comment by saumyalahera** [comment]
I figured that thing out, however undo and redo don't work. Can you tell me how should I do that? Is there an initial setup for that?

**Comment by Harley-xk** [comment]
@saumyalahera First of all, make sure you are using the latest version. There's no property named `brush` on canvas.
 A brush must be registered to canvas before painting with it. You can create a brush by calling the `registerBrush` method on canvas directly.  Then, call `brush.use()` on brush witch you want to use.
And in the latest version, undo and redo features are automatically set up.
