### ISSUE TITLE
Last update broke some brushes

### ISSUE THREAD

**Issue by DamienBell** [Harley-xk/MaLiang#42]
It looks like the one of the recent updates broke the pencil, brush and claw brushes. There's no output on those strokes.

**Comment by Harley-xk** [comment]
Have you updated MaLiang to the latest version? I'm not sure witch version are you currently using.

**Comment by Joey-Lee** [comment]
I meet the issue with the latest version.

**Comment by Harley-xk** [comment]
@Joey-Lee Have you tried to clean the build folder in Xcode, there are always some building cache causing strange problems
