### ISSUE TITLE
writing W's

### ISSUE THREAD

**Issue by abrpatel** [Harley-xk/MaLiang#45]
for some reason when you write W's on canvas it doesn't render properly compared to alternative drawing programs. This is in particular when you try to write small W's. Only the last stroke for the w is registered giving it a V shape instead of a W.

For example, this is how it appears in the demo app:
![IMG_2156](https://user-images.githubusercontent.com/947100/58059293-ccbc0980-7b31-11e9-8a8e-29e4906ffa2e.PNG)

and this is how w's show up in paper:
![IMG_2157](https://user-images.githubusercontent.com/947100/58059319-e8271480-7b31-11e9-9867-f98873efe46a.PNG)

Do you know what the issue is and how it might be resolved?

**Comment by Harley-xk** [comment]
It seems that the accuracy of line positions needs to be improved when calculating bezier path.

**Comment by abrpatel** [comment]
Is it very complicated to do?

**Comment by Harley-xk** [comment]
Yes, a little complicated. But this is something really needs to be done. I will do it later when I have enough time.

**Comment by abrpatel** [comment]
Awesome!

**Comment by abrpatel** [comment]
Found this library that does the calculations so you don't have to. https://github.com/uber/UberSignature

![IMG_2159](https://user-images.githubusercontent.com/947100/58183989-e36b7900-7c75-11e9-93fb-d0e245f079de.PNG)

**Comment by abrpatel** [comment]
Found an codebase that might be helpful: https://github.com/slade9220/ZenBoard

**Comment by Harley-xk** [comment]
Very thanks! I'will read these code later

**Comment by abrpatel** [comment]
Any progress?

**Comment by Harley-xk** [comment]
not yet

**Comment by Harley-xk** [comment]
@abrpatel fixed now, try out the 2.6.0 version.
Please noticed that forceEnabled is deprecated on this version, and it's turned on by default.
and simulated force is removed too.

**Comment by abrpatel** [comment]
Works beautifully!!
