### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by hamzaben1** [Harley-xk/MaLiang#49]
Thank you for such an awesome library! Its helping me. However, a crash occurred multiple times in my console .

at let textureLoader = MTKTextureLoader(device: device!)

library version - 2.6.1
with ios version: 10.3.3 and 9.3.5

[log.pdf](https://github.com/Harley-xk/MaLiang/files/3401903/log.pdf)

**Comment by Harley-xk** [comment]
it seems that you are not running Metal on a supported device. What kind of device are you using?
try calling `MTLCreateSystemDefaultDevice()`  and see what this function returns

**Comment by hamzaben1** [comment]
can i identify if a device support metal at runtime ??

**Comment by Harley-xk** [comment]
In Metal, `Device` is the abstract for GPU. On iOS devices, there''s only one GPU, so you can get that device by calling `MTLCreateSystemDefaultDevice()`, this function will return the supported device, if your iOS device does not support Metal, this function will return nil.
On macOS, you can  call `MTLCopyAllDevices()`, this function will return all GPUs that are supporting Metal.
And there's a simple way:
- On iOS, Metal supports devices with Apple A7 or newer, witch comes with iPhone 5S, iPad Air and iPad mini 2.
- MaLiang is based on MetalKit, witch comes with iOS 9.
So, the oldest supported devices are iPhone 5S, iPad Air and iPad mini 2; the minimum supported system is iOS 9.

**Comment by hamzaben1** [comment]
Thank you very much. I really appreciate your explanation.
