### ISSUE TITLE
Cannot use Canvas(frame: CGRect)

### ISSUE THREAD

**Issue by zenkog** [Harley-xk/MaLiang#5]
Hi, 
I have problem using the classes defined in MaLiang.
I have installed the pods and imported MaLiang inside the project. 
Then I have make sure that the Maliang folder is in my project's Pod folder. This much is working.
But for some unknown reason, the Canvas class cannot be detected properly. It doesn't show the Canvas(frame:CGRect). Also the Brush is different and Bundle has conflict, not with my code but with some core codes from Xcode. I have tried Clean and re-build, also reinstall pods. All doesn't work

Do you know whats wrong?

**Comment by Harley-xk** [comment]
What is the version of your Xcode and Swift?
MaLiang requires Swift 4.1, witch comes along with Xcode 9.3.

**Comment by zenkog** [comment]
Yes I have used the version 9.3

**Comment by zenkog** [comment]
Here are some screenshots. Showing:
1. The Podfile is installed and all files are inside Pod
2. Imported MaLiang without problem
3. Canvas(Frame) still cannot detected. And I have tried to build it but still failed.

I always clean and build again after every new pod install and import

See the files below:

![canvas frame not detected](https://user-images.githubusercontent.com/38452853/40265874-4541b470-5b73-11e8-8638-d24b01734fe9.jpg)
![podfile installed](https://user-images.githubusercontent.com/38452853/40265875-458220d2-5b73-11e8-8910-e53f197143be.jpg)
<img width="476" alt="imported" src="https://user-images.githubusercontent.com/38452853/40265876-45bf47d2-5b73-11e8-80e7-ccc94df2ff84.png">

**Comment by Harley-xk** [comment]
As I can see, there's no problem, maybe there's something wrong with your Xcode's build system or auto completion system...
Try to enable the new build system and build again?

![image](https://user-images.githubusercontent.com/12761885/40274715-bbcf8a2a-5c10-11e8-9f7c-dd0be01a3f5b.png)

**Comment by zenkog** [comment]
Hi, I have trying to figure this thing out for many days now. And I just found out that the Pod files you provided in Cocoapods is outdated. 

You can see that in the MaLiang's example there is this part of the code inside MLView.swift
    // MARK: - Initialize
    public override init(frame: CGRect) {
        super.init(frame: frame)
        setup()
    }

But in the Cocoapods version that I have installed doesn't have. You can see the attached file.
So can you update that? or do you have other suggestions?


<img width="1304" alt="my code" src="https://user-images.githubusercontent.com/38452853/40405972-5b00783e-5e91-11e8-9792-6c22c3d0d633.png">
<img width="1392" alt="maliang example codes" src="https://user-images.githubusercontent.com/38452853/40405973-5b39221a-5e91-11e8-869a-071b9ba74bc5.png">



Thank you

**Comment by Harley-xk** [comment]
@zenkog What's the version of MaLiang you have installed?  You can check it in your podfile.lock, The latest version in Cocoapods is 1.1.3.  I think you have installed an old version.

**Comment by zenkog** [comment]
Hi, I have tried to reinstall it but its always the old version. Then I found out that if you check in Cocoapod website you can see that your MaLiang Code is stored there is version 0.1.0. See the screenshot. this is why cannot upgrade. please check it.
![screen shot 2018-05-23 at 9 53 28 pm](https://user-images.githubusercontent.com/38452853/40428991-1da10362-5ed4-11e8-89eb-b492870c0ec8.png)

**Comment by zenkog** [comment]
So I also tried to specify the version by:

pod 'MaLiang', '~> 1.1.3'

But it failed upon update:

<img width="682" alt="screen shot 2018-05-23 at 10 00 53 pm" src="https://user-images.githubusercontent.com/38452853/40429334-0b8aaede-5ed5-11e8-9008-2c674ad1d9a2.png">

**Comment by Harley-xk** [comment]
use `pod update MaLiang` to update it

**Comment by zenkog** [comment]
After "pod update MaLiang", its only updating to ver 0.5.0.
How to get the ver 1.1.3 ?

<img width="697" alt="screen shot 2018-05-25 at 1 07 32 pm" src="https://user-images.githubusercontent.com/38452853/40527086-ff5f84ba-601c-11e8-800f-b071ba35ffb5.png">
