### ISSUE TITLE
有没有办法在截取涂鸦的时候，只截取涂鸦的部分呢？

### ISSUE THREAD

**Issue by ZikeX** [Harley-xk/MaLiang#53]
一个纹理作为背景，然后我在背景上进行涂鸦，在保存图片的时候，只截取还有涂鸦部分的背景图呢？

**Comment by Harley-xk** [comment]
目前画布上固定只有一个图层，如果把背景也以纹理的形式绘制到画布上，截图的时候是没办法知道哪些内容需要排除掉的。
可以参考示例项目中背景图的实现，把背景图作为单独的视图放到`Canvas`后面显示，因为画布默认是透明的，因此也可以实现在背景图上涂鸦的效果，同时对画布单独截图时可以得到透明背景的涂鸦内容。
等开发 3.0 的时候可能会考虑实现多图层的逻辑。

**Comment by ZikeX** [comment]
谢谢！
最近在新CutCut这个类似的app，参考了这个库，获益良多。非常感谢！
