### ISSUE TITLE
Conflicting Init method from PaintingGestureRecognizer Class with the superclass UIPanGestureRecognizer

### ISSUE THREAD

**Issue by zenkog** [Harley-xk/MaLiang#6]
Hi, I got an error when building the files even before using the class or method at all. This is just after installing pods.
My MaLiang version is 1.1.3

The error is:
"Initializer 'init(target:action:)' with Objective-C selector 'initWithTarget:action:' conflicts with implicit initializer 'init(target:action:)' from superclass 'UIPanGestureRecognizer' with the same Objective-C selector"

<img width="1205" alt="screen shot 2018-05-25 at 1 22 27 pm" src="https://user-images.githubusercontent.com/38452853/40527468-48dbedac-601f-11e8-8dd9-d0974cef1462.png">

**Comment by Harley-xk** [comment]
Are you using MaLiang in an Objective-C project?  It's not compatible with Objective-C Now.

**Comment by zenkog** [comment]
My project was in Objective-C before. But now most of it is in Swift already. All new codes are in swift.

**Comment by Harley-xk** [comment]
emm....Maybe I should rename that function to avoid the conflect.

**Comment by Harley-xk** [comment]
@zenkog try again with the new version 1.1.5.

**Comment by zenkog** [comment]
IT WORKED!! Thank you!!

**Comment by Harley-xk** [comment]
😃Happy to see this!
