### ISSUE TITLE
马克笔

### ISSUE THREAD

**Issue by dongshangtong** [Harley-xk/MaLiang#65]
大神，你好呀！我看很多APP都马克笔工具，希望您能在框架里多增加马克笔工具？谢谢您了！

**Comment by Harley-xk** [comment]
你说的马克笔是什么样的效果，有没有截图参考下？
另外 `MaLiang` 提供了画笔定制的功能，理论上能实现很多画笔的效果，所以并没有打算在框架里实现具体的画笔，而是留给上层去实现的。

**Comment by dongshangtong** [comment]
嗯，这个两张参考图苹果自带的APP“备忘录” 和 另一个APP“柔记”, 还有我觉得写你的画板缩放功能没有那么流畅，你可以参考柔记缩放功能流畅。
![备忘录](https://user-images.githubusercontent.com/12619698/69305857-6c349300-0c60-11ea-88cf-bd6fd26cef05.jpg)
### ![柔记](https://user-images.githubusercontent.com/12619698/69305860-6f2f8380-0c60-11ea-9774-eb0dd179697c.png)

**Comment by Harley-xk** [comment]
这个效果很好实现，参考 demo 里面钢笔的实现，换一个扁的纹理并降低一些透明度就可以了
