### ISSUE TITLE
移植到Mac上背景色错误

### ISSUE THREAD

**Issue by joguo** [Harley-xk/MaLiang#67]
我尝试将MaLiang库移植到Mac app上运行，删除了iOS only的部分内容，运行后，Canvas的背景色为红色，而不是iOS上的透明色，请问可能是哪些原因引起的？ 
或者是我哪里修改错误了吗？
[https://github.com/joguo/MaliangMTK.git](url)

**Comment by LiJian-China** [comment]
请问楼主的问题解决了吗？我也是移植到Mac app上 背景是红色。无法更改。

**Comment by joguo** [comment]
已确定是Mac 10.15的bug。我在其他系统的设备上验证时，没有红色的问题。

**Comment by Zss1990** [comment]
我的Macos 11.6.1仍是有这个问题的
