### ISSUE TITLE
registerChartlet function doesn't exist?

### ISSUE THREAD

**Issue by hartwoolery** [Harley-xk/MaLiang#69]
`let data = UIImage(named: "chartlet").pngData()
try canvas.registerChartlet(with: data)`

results in error:  Value of type 'Canvas' has no member 'registerChartlet'

Using latest version 2.6.3

**Comment by Harley-xk** [comment]
It's a mistake in document, use codes below to render a chartlet:
```swift
let data = UIImage(named: "chartlet").pngData()
let texture = try canvas.makeTexture(with: data)
canvas.renderChartlet(at: location, size: chartletSize, textureID: texture.id, rotation: angle)
```
