### ISSUE TITLE
Header MaLiang-Swift.h Not found

### ISSUE THREAD

**Issue by zenkog** [Harley-xk/MaLiang#7]
I got some strange error just after updating to ver 1.1.3 using 'pod update MaLiang' command
It says that header MaLiang-Swift.h is not found. I checked it and it wasn't there.
See the attached screen shot

<img width="912" alt="screen shot 2018-05-25 at 1 22 49 pm" src="https://user-images.githubusercontent.com/38452853/40527548-9f20fe64-601f-11e8-8ed1-eb796be278b7.png">

**Comment by Harley-xk** [comment]
Added SWIFT_VERSION config in version 1.1.4.
But as mentioned in #6 , MaLiang is not compatible with Objective-C project now.

**Comment by zenkog** [comment]
Now it Worked in Ver 1.1.5
