### ISSUE TITLE
内存问题

### ISSUE THREAD

**Issue by fangandyuan** [Harley-xk/MaLiang#72]
画板好像初始化就需要45MB左右,这是不是有点过于大?这是因为什么特殊原因才需要这么大的内存吗?

**Comment by fangandyuan** [comment]
内存会不断增大.这个问题还挺严重的.而且我们清空画板后也没有恢复

**Comment by youzige** [comment]
同问，CPU占用也会飙升，手机发烫

**Comment by codejun9527** [comment]
大佬解决了吗？

**Comment by youzige** [comment]
清空画板后调用一下resetData()，内存问题可以解决。
