### ISSUE TITLE
Painting into a mask

### ISSUE THREAD

**Issue by mediaRare** [Harley-xk/MaLiang#79]
Hello - I need to be able to paint only in a masked area.

Can you tell how that could be done?

Many thanks.

**Comment by askrav-anoda** [comment]
I'm also interested in what's the best way to implement this feature. For example, limit the drawing area within the closest bounds of an SVG image..

**Comment by mediaRare** [comment]
In the end I got a great solution to this. Very accurate.

**Comment by askrav** [comment]
> In the end I got a great solution to this. Very accurate.

Awesome! Is it possible to share the algorithm or the code so I could try it?

**Comment by mediaRare** [comment]
Let me know if you need some explanation:

override func touchesEnded(_ touches: Set<UITouch>, with event: UIEvent?) {
    if !swiped {
      // draw a single point
      drawLine(from: lastPoint, to: lastPoint)
    }
    
    // Merge tempImageView into mainImageView
    UIGraphicsBeginImageContext(mainImageView.frame.size)
    mainImageView.image?.draw(in: view.bounds, blendMode: .normal, alpha: 1.0)
    tempImageView?.image?.draw(in: view.bounds, blendMode: .normal, alpha: opacity)
    mainImageView.image = UIGraphicsGetImageFromCurrentImageContext()
    UIGraphicsEndImageContext()
    
    print("currentBodyMask = \(currentBodyMask)")
    let maskImageview   = UIImageView()
    maskImageview.image = UIImage(named: currentBodyMask)
    
    maskImageview.contentMode = .scaleAspectFit
    maskImageview.frame = mainImageView.bounds
    print(mainImageView.bounds)

    mainImageView.mask = maskImageview
    tempImageView.image = nil
    
  }

Mask image example:

![Female-Front-Mask-375x663px](https://user-images.githubusercontent.com/59351258/86463766-48483c80-bd6d-11ea-8727-2241d32b5d8a.png)

**Comment by askrav-anoda** [comment]
Many thanks!

**Comment by 1729patrick** [comment]
Thanks, guys! @askrav-anoda  @askrav, did you manage to mask the drawing to the closest path of an SVG/Shape?
