### ISSUE TITLE
丢笔

### ISSUE THREAD

**Issue by pEnG1ShiXiN** [Harley-xk/MaLiang#8]
我在学习ios 的opengl技术,我想请教下,为什么我在比较快的情况下画笔会出现丢笔的情况

**Comment by Harley-xk** [comment]
请问具体现象是什么样的，最好能提供截图等，方便定位具体问题。
另外请提供下你使用的 MaLiang 的具体版本号。

**Comment by pEnG1ShiXiN** [comment]
比如我在写"3+2=5",等号比较容易出不来 版本号应该是1.1.2

**Comment by Harley-xk** [comment]
嗯，与滑动手势的误差有关，尽量避免画太短的线条；
后续应该会对这个问题做优化。

**Comment by Harley-xk** [comment]
计算贝塞尔曲线的算法出现了空档导致某些情况下画不出来，已在 1.1.6 版本中修复
