### ISSUE TITLE
Drawing below chartlets

### ISSUE THREAD

**Issue by askrav-anoda** [Harley-xk/MaLiang#87]
I've been investigating this great library for a couple of days and I'm wondering if there's a way to bring all the chartlets to the "front" so that the drawing lines would always render below them? Right now when I add a chartlet to the canvas I can draw on top of it.
I tried modifying `position.z`of the output vertex in shaders methods `vertex_point_func` and `vertex_printer_func` but it didn't help, unfortunately. 
Would appreciate any help.

**Comment by Harley-xk** [comment]
@askrav-anoda See the `data` property on Canvas, it stores all the `CanvasElement` in an array called `elements`. You can modify or resort this array as you like, and then call the `redraw()` method on Canvas. All the elements will be drawed by their 
order in the `elements` array. `CanvasElement` is a protocol, `Chartlet` and `LineStrip` both have Implemented this.

**Comment by askrav-anoda** [comment]
Hi @Harley-xk , thanks for your suggestion! 
I thought about such a solution but this would mean calling the `redraw` method every time the user moves his finger so each new `LineStrip`would be rendered below all the chartlets on the canvas. And probably additional changes in order to keep the "Undo" action working. 
Is there a chance to do it the "Metal" way?

**Comment by Harley-xk** [comment]
@askrav-anoda  Yes, the `redraw` method has performance issue now. A better way to do this is to keep mutiple layers on the same view like PhotoShop do. But Maliang currently supports only one layer.

**Comment by askrav-anoda** [comment]
Alright, thanks for your comments. I'll take a closer look again and hopefully find a clean solution for this.
