### ISSUE TITLE
There has redo issues on some device

### ISSUE THREAD

**Issue by stonexing** [Harley-xk/MaLiang#88]
The issues only appear on some device. not all device

video is take on: i7-3770, GTX760, iOS13.6 11 pro max Simulator, 

[屏幕录制2020-07-23 下午5.52.19.zip](https://github.com/Harley-xk/MaLiang/files/4965210/2020-07-23.5.52.19.zip)

**Comment by Harley-xk** [comment]
Have this issue appear on any real device? It looks like the touches is interrupted in the video.

**Comment by stonexing** [comment]
Only appear Simulator's (both 13.0 and 13.6) on my Desktop hackintosh PC. with CPU i7-3770
Another laptop with CPU i7-8550 is running with no this issue.
All real device (I test on 5s, 7,  x) are running with no this issue.

**Comment by Harley-xk** [comment]
So, it seems like a hardware or system issue with mouse pointer on the hackintosh or its simiulator, just ignore it.
