### ISSUE TITLE
如何用Chartlet来当做画笔

### ISSUE THREAD

**Issue by UnicornBoss** [Harley-xk/MaLiang#89]
大概效果是这样

![Jietu20200825-151041-HD](https://user-images.githubusercontent.com/29502440/91143684-7dc23400-e6e5-11ea-86e7-2c3db813f399.gif)

**Comment by Harley-xk** [comment]
写一个支持彩色纹理的着色器应该可以实现，我找时间尝试一下

**Comment by UnicornBoss** [comment]
嗯嗯，谢谢大佬

**Comment by codejun9527** [comment]
应该写一个直接插图的画笔

**Comment by Harley-xk** [comment]
@codejun9527 是的，彩色的纹理着色器其实在写贴图的时候已经实现了，所以只要把贴图的功能整合到画笔中就可以了

**Comment by ZCApple** [comment]
有没有已经扩展出来的兄弟啊？尝试着写了一下，感觉有困难...

**Comment by UnicornBoss** [comment]
> 有没有已经扩展出来的兄弟啊？尝试着写了一下，感觉有困难...

你是不是接了一个叫可可修图的外包项目

**Comment by ZCApple** [comment]
> > 有没有已经扩展出来的兄弟啊？尝试着写了一下，感觉有困难...
> 
> @ZCApple 你是不是接了一个叫可可修图的外包项目

没有...目前项目里要求做这个功能

**Comment by Harley-xk** [comment]
核心逻辑已经写完了，正在调整一些细节，预计这两天会发出来

**Comment by coderjun666** [comment]
扩展出来的一个插图的笔触
![图像 3](https://user-images.githubusercontent.com/52390325/97142570-d1133a00-179b-11eb-875f-3de767145a83.GIF)

**Comment by Harley-xk** [comment]
2.9.0 新增了 `ChartletBrush`，支持使用一个或多个图片作为纹理，支持纹理旋转，可以在示例项目中查看使用方法。

**Comment by coderjun666** [comment]
> 2.9.0 新增了 `ChartletBrush`，支持使用一个或多个图片作为纹理，支持纹理旋转，可以在示例项目中查看使用方法。

期待大佬可以早日拾起这个 插图brush时表现很明显
[性能问题](https://github.com/Harley-xk/MaLiang/issues/85)

**Comment by Harley-xk** [comment]
@coderjun666  在研究了~

**Comment by CHPisces** [comment]
> 插图笔触
> 
> ![图像 3](https://user-images.githubusercontent.com/52390325/97142570-d1133a00-179b-11eb-875f-3de767145a83.GIF) [ ![图像 3](https://user-images.githubusercontent.com/52390325/97142570-d1133a00-179b-11eb-875f-3de767145a83.GIF) ](https://user-images.githubusercontent.com/52390325/97142570-d1133a00-179b-11eb-875f-3de767145a83.GIF) [ ](https://user-images.githubusercontent.com/52390325/97142570-d1133a00-179b-11eb-875f-3de767145a83.GIF)

这个是其他方案实现的吗？
