### ISSUE TITLE
Modifying to detect a line

### ISSUE THREAD

**Issue by zenkog** [Harley-xk/MaLiang#9]
Hi,
In my app, I want the painting to be able to detect if it reaches the edge. Its painting on PNG format with black line alpha 0.5-1, the rest are transparent.
I found that your code handles all the painting in the MaLiang podfile. 

Thus, which class and method should I override so when we detect the edges, it will stop coloring. Then it will begin coloring again when getting back in. This happens even user have not lift up his/her fingers.
Or do you have a method that I can call to enable/disable painting?
Any suggestions?

**Comment by Harley-xk** [comment]
Set the property `isUserInteractionEnabled` of Canvas to `false` may help.
How do you paint on Canvas? Via gestures or directly call the function `renderLine`?
If you are painting with gestures, set this property to `false` when painting needs to be disabled.
Or, the other way, just set `isUserInteractionEnabled` to `false` all the time，and call the `renderLine` function manually with your own logic.
