### ISSUE TITLE
PointSize and PointStep don't belong to MLLine

### ISSUE THREAD

**Issue by ulitiy** [Harley-xk/MaLiang#90]
PointSize and PointStep are the properties of the brush, they shouldn't be cached in the MLLine. MLLine should store force but not the size as it should be able to be rendered with any brush. So when LineStrip calculates vertex size It should take the force of the MLLine and size of the brush. It's much more flexible and architecturally correct IMO.

The current way it embeds part of the brush properties and the line cannot be reused to be rendered to another target texture with another brush.

**Comment by ulitiy** [comment]
Brush should only be used when rendering the strip, not when assembling it. It's much better to be able to change the brush of the entire strip, not the individual fragments of it. I cannot imagine someone changing the brush in the middle of the stroke.

**Comment by Harley-xk** [comment]
Not agree. All lines and strips are not designed for reusing, they are designed for persistance. these lines should not be changed to another apperance once they are painted. So the saved data can be transformed to another device and recovered to what it is. And the color for eche fragments of a line strip makes it posiable to paint gradient lines.

**Comment by ulitiy** [comment]
I see your point, thank you! Though I would prefer vector-like behaviour where one could change the style of the strip after drawing it.
