### ISSUE TITLE
need help with eraser tool

### ISSUE THREAD

**Issue by VJosan** [Harley-xk/MaLiang#97]
hello, can someone help me to add border to eraser tool, so i want to see border of brush when i am erasing

**Comment by Harley-xk** [comment]
In the latest version(2.9.0), There’re methods called ‘renderBegan(from:on:)’, ‘renderMoved(to:on:)’ and ‘renderEnded(at:on:)’ in class Brush. These methods are called when touches ware began, moved or ended. You can add an image with frame of your eraser and update its position in these methods.
