### ISSUE TITLE
iOS14  image brush makeTexture的效果与iOS13不同

### ISSUE THREAD

**Issue by coderjun666** [Harley-xk/MaLiang#98]
![image](https://user-images.githubusercontent.com/52390325/96072400-d1c3ea80-0ed6-11eb-965d-d50d0781d8d9.jpeg)![image](https://user-images.githubusercontent.com/52390325/96072406-d5f00800-0ed6-11eb-823a-7b8469529ae2.jpeg)

同一份code，不同系统的表现不同，大佬帮忙看看

**Comment by coderjun666** [comment]
demo跑也一样
iOS13
![image](https://user-images.githubusercontent.com/52390325/96087310-3b9fbc80-0ef6-11eb-8280-fe5849b6d226.png)

iOS14
![image](https://user-images.githubusercontent.com/52390325/96087355-4d815f80-0ef6-11eb-95f2-5abd6a4b3474.jpeg)

笔触素材
![image](https://user-images.githubusercontent.com/52390325/96087373-55410400-0ef6-11eb-9ec3-e68afce2e836.jpeg)

**Comment by Harley-xk** [comment]
@coderjun666  你贴的这个素材是 jpg 的，有 png 的原始图吗?

**Comment by coderjun666** [comment]
> @coderjun666 你贴的这个素材是 jpg 的，有 png 的原始图吗?
![星星／平铺-紫色@2x](https://user-images.githubusercontent.com/52390325/96205693-d3a2b200-0f99-11eb-8667-7d96ba1848ee.png)

**Comment by Harley-xk** [comment]
贴图的混合参数写错了 😓
@coderjun666  更新到 2.8.3 试一下，应该可以了

**Comment by coderjun666** [comment]
> 贴图的混合参数写错了 😓
> 
> @coderjun666  更新到 2.8.3 试一下，应该可以了

哈哈哈 可以贴一下代码吗？麻烦大佬了

**Comment by Harley-xk** [comment]
混合参数就在 'Printer.swift' 这个类的 'setupBlendOptions' 方法里设置的，你可以找一下源代码
